### ISSUE TITLE
FPM in GitHub Actions

### ISSUE THREAD

**Issue by jacobwilliams** [szaghi/FACE#11]
FYI: there's a [setup-fpm](https://github.com/fortran-lang/setup-fpm) GitHub Action that makes it easy to use FPM in the CI. Basically you just need this:

```yml
    - name: Setup Fortran Package Manager
      uses: fortran-lang/setup-fpm@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
```
